#!/bin/bash

function auto-generate-all() {
    pushd $AUTOGENERATEDIR/Data

    # remove all files
    find . -name '*.cs' -type f -exec trash {} +

    # re-generate grpc files
    $BASEDIR/protoc --plugin=protoc-gen-grpc=$BASEDIR/grpc_csharp_plugin --csharp_out=. \
        --grpc_out=. --grpc_opt=no_server \
        --proto_path=$PROTODIR/data $PROTODIR/data/*.proto

    popd

    pushd $AUTOGENERATEDIR/Service

    # remove all files
    find . -name '*.cs' -type f -exec trash {} +

    # re-generate grpc files
    $BASEDIR/protoc --plugin=protoc-gen-grpc=$BASEDIR/grpc_csharp_plugin --csharp_out=. \
        --grpc_out=. --grpc_opt=no_server \
        --proto_path=$PROTODIR/service $PROTODIR/service/*.proto

    popd
}

function update-proto() {
    pushd $PROTODIR

    git pull

    popd

    auto-generate-all
}

BASEDIR="$(cd "$(dirname "$0")"; pwd)"
PROTODIR="$BASEDIR/../eva_proto"
AUTOGENERATEDIR="$BASEDIR/../Assets/1_Scripts/Network/Grpc/Generated"

case "$1" in
    auto-generate-all)
        auto-generate-all
        ;;
    update-proto)
        update-proto
        ;;
    *)
        echo "invalid"
        ;;
esac
